### ISSUE TITLE
Fix for the 16x8 LED backpack

### ISSUE THREAD

**Issue by TwystNeko** [adafruit/Adafruit-LED-Backpack-Library#7]
So the 16x8 backpack doesn't fully work with the Adafruit_GFX library. I added code to let all the drawing commands work. 

in Adafruit_LEDBackpack.h:

```
class Adafruit_8x16matrix : public Adafruit_LEDBackpack, public Adafruit_GFX { 
  public:
    Adafruit_8x16matrix(void);

    void drawPixel(int16_t x, int16_t y, uint16_t color);
    private:
};
```

in Adafruit_LEDBackpack.cpp:

```
Adafruit_8x16matrix::Adafruit_8x16matrix(void) : Adafruit_GFX(8, 16) {
}

void Adafruit_8x16matrix::drawPixel(int16_t x, int16_t y, uint16_t color) {

  if ((y < 0) || (y >= 16)) return;
  if ((x < 0) || (x >= 8)) return;
switch (getRotation()) {
  case 1:
    swap(x, y);
    x = 8 - x - 1;
    break;
  case 2:
    x = 8 - x - 1;
    y = 16 - y - 1;
    break;
  case 3:
    swap(x, y);
    y = 16 - y - 1;
    break;
  }


  if (color) {
    displaybuffer[x] |= 1 << y;
  } else {
    displaybuffer[x] &= ~(1 << y);
  }

}
```

It's not perfect, and it's a bit customized to my specific application - I removed the x-axis wraparound. But with those two code blocks, I can use all the primitives.

**Comment by bperrybap** [comment]
I agree with TwystNeko that there are Adafruit 16x8 products including some with two 8x8 matrices so things could be better, but I don't agree with his "fix" since it moved the x/y sanity checks to before the rotation corrects them for the orientation and it is also jumbling up the 16x8 and 8x16 orientations to create a 16x8 display orientation.
(What is needed is a 16x8 class that has a default orientation of 16x8)

I brought up the 16x8 vs 8x16 in issue #13 back Aug 2014.

The issue here is two fold.
- There is no documentation that explains how to wire up the 16x8 module Cx an Ax pins to a matrix
(I'll be creating a new issue for this, since the wiring is non obvious particularly for the 8x8)
- The matrix can be thought of as 16x8 or 8x16, but the product information for the "backpack" calls it 16x8


The existing code and constructor assumes a 8x16 arrangement.
It can be rotated to be 16x8 by setting the rotation to 1; however, in my view the 8x16 arrangement is not a good default, especially given the wiring the code requires to make it work and the names of the actual adafruit products that would be using it are calling it a 16x8 matrix. 
At a minimum for a 8x16 matrix, the wiring is funky and inconsistent with the way matrices are typically wired up
(however, as I'll show, the wiring *is* correct and great for a 16x8 orientation)

This starts to become clearer once the wiring for the matrixes is actually documented

Look at how the code assumes a matrix is wired. I'll use the labels on the physical PCB rather than the terminology in the datasheet to keep things consistent.
```
  c7 c6 c5 c4 c3 c2 c1 c0
a0
a1
a2
a3
a4
a5
a7
a8
a9
a10
a11
a12
a13
a14
a15
```

The code maps the upper left corner to 0,0 and increasing x moves to the right and increasing y values move down.
The thing to note here is that the default orientation requires the columns
to be wired up with the Cx pins wired "backwards" with respect to the x values.
i.e. pixel 0,0 is C7,A0 | pixel 1,0 is C6,A0 ... 0,7 is C0,A0
Typically, to keep things simple, the h/w lines are wired in the same order as the
s/w pixel x,y coordinates.
Because the Cx lines are wired backwards with respect to the x coordinate when
using a 8x16 orientation, you have to reverse the final x coordinate.

However, if you rotate the same matrix 90 degrees counter clockwise, and use the same wiring, you end up with this matrix:
```
 a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15
c0
c1
c2
c3
c4
c5
c7
```

And now it is nice clean and simple wiring.
The x values increase to the right the same as the An pins and the y values increase the same as the Cn pins.

While rotation 1 with the existing 8x16 matrix will also get you to this point it seems much clearer and intuitive to use a 16x8 default orientation with the given wiring so that the default gives you this.

Also, if you look at the existing drawPixel() code in the Adafruit_8x16matrix class, you see that there is y pixel value flipping being done. Clearly the default wiring does not work with the default rotation which is another indication that 16x8 would be a better default orientation for this wiring.

And even further, why not have a class name that matches the product names?
The products call it a 16x8 matrix, so why not have the library class to match?

I'd recommend leaving the wiring alone, but create a 16x8  class to solve this. The existing 8x16 class can be deprecated but remain in the code for those that may be already using it.
